[terminal]
vt = 1

[default_session]
command = "tuigreet --theme 'border=cyan;container=black;button=cyan' --cmd 'env XDG_SESSION_TYPE=wayland XDG_CURRENT_DESKTOP=niri XDG_SESSION_DESKTOP=niri dbus-run-session -- niri'"

user = "greeter"
